-- nit initial schema, MySQL and MariaDB.
--
-- The same version number as migrations/postgres/0001_init.up.sql, describing
-- the same schema. It is hand-written rather than translated: the places the
-- two dialects diverge are the places a reader needs to see, and each one is
-- commented where it occurs.
--
-- Requires MySQL 8.0.16+ or MariaDB 10.6+. Below those, CHECK constraints are
-- parsed and ignored (MySQL) or SKIP LOCKED is missing (MariaDB) — in both
-- cases the engine would accept this file and then fail to enforce what the
-- queue depends on.
--
-- The two principles of the PostgreSQL schema hold unchanged. Policy is not
-- stored here; the rows below mirror the YAML bundle only where a foreign key
-- needs something to point at. And tenant_id is present on every table even
-- though nit ships single-tenant, because threading a tenant through a schema
-- after the fact is one of the most expensive migrations there is.
--
-- Four dialect decisions run through the whole file.
--
-- 1. Identifiers are CHAR(36) and generated by the application. Neither engine
--    has UPDATE ... RETURNING, and INSERT ... RETURNING exists only in MariaDB,
--    so the application has to know the id it is inserting in any case.
--    Generating it in Go removes a round trip and a dialect difference at once.
--
-- 2. Every table is utf8mb4_bin. PostgreSQL compares text byte by byte; the
--    default collations here do not, and they do not even agree with each other
--    (utf8mb4_0900_ai_ci on MySQL, utf8mb4_uca1400_ai_ci on recent MariaDB).
--    Left to the defaults, "Maya" and "maya" would collide in
--    users_policy_id_unique on one backend and not on the other — a difference
--    in an authorization join, which is the last place to accept one.
--
-- 3. Timestamps are DATETIME(6), holding UTC. TIMESTAMP would be the closer
--    analogue of TIMESTAMPTZ but tops out in 2038 on MySQL, and an expiry date
--    is exactly the kind of column that reaches for a far future. The driver
--    DSN must set parseTime=true and loc=UTC; internal/store/mysql refuses a
--    DSN that does not.
--
-- 4. There are no partial indexes. Each one below is a full index where
--    PostgreSQL has a filtered one, so they cost more to maintain and are less
--    selective. Noted at each site rather than silently accepted.

-- ============================================================================
-- TENANTS
-- ============================================================================

CREATE TABLE tenants (
    id          VARCHAR(64) NOT NULL,
    name        TEXT NOT NULL,
    created_at  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

INSERT INTO tenants (id, name) VALUES ('default', 'Default tenant');

-- ============================================================================
-- IDENTITY
-- ============================================================================

-- A person. policy_user_id is the id used in the policy bundle; it is the join
-- between authorization decisions and stored state.
CREATE TABLE users (
    id              CHAR(36) NOT NULL,
    tenant_id       VARCHAR(64) NOT NULL,

    -- VARCHAR rather than TEXT: it is part of a unique key, and MySQL cannot
    -- index a TEXT column without a prefix length. The limit is a real one,
    -- where PostgreSQL has none.
    policy_user_id  VARCHAR(255) NOT NULL,
    email           VARCHAR(320) NOT NULL,
    display_name    TEXT NOT NULL,

    disabled        TINYINT(1) NOT NULL DEFAULT 0,

    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT users_policy_id_unique UNIQUE (tenant_id, policy_user_id),
    CONSTRAINT users_policy_id_not_empty CHECK (CHAR_LENGTH(TRIM(policy_user_id)) > 0),
    CONSTRAINT users_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- Authentication tokens issued to CLI installations.
--
-- Only the hash is stored: a leaked database dump must not yield usable
-- credentials.
CREATE TABLE sessions (
    id           CHAR(36) NOT NULL,
    tenant_id    VARCHAR(64) NOT NULL,
    user_id      CHAR(36) NOT NULL,

    -- VARBINARY, not BLOB: a unique key needs a fixed length. 64 bytes leaves
    -- room above the 32 a SHA-256 takes.
    token_hash   VARBINARY(64) NOT NULL,
    label        TEXT NOT NULL,

    created_at   DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at   DATETIME(6) NULL,
    last_used_at DATETIME(6) NULL,
    revoked_at   DATETIME(6) NULL,

    PRIMARY KEY (id),
    CONSTRAINT sessions_token_hash_unique UNIQUE (token_hash),
    CONSTRAINT sessions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- PostgreSQL indexes only the live sessions (WHERE revoked_at IS NULL). Here
-- the index covers revoked ones too, which is the cost of no partial indexes:
-- a tenant that revokes often carries dead entries in a hot index.
CREATE INDEX idx_sessions_user ON sessions(user_id);

-- One checkout on one machine. Sync points are per workspace, which is what
-- lets a developer use a laptop and a desktop without corrupting either.
CREATE TABLE workspaces (
    id            CHAR(36) NOT NULL,
    tenant_id     VARCHAR(64) NOT NULL,
    user_id       CHAR(36) NOT NULL,

    label         TEXT NOT NULL,

    created_at    DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_seen_at  DATETIME(6) NULL,

    PRIMARY KEY (id),
    CONSTRAINT workspaces_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT workspaces_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

CREATE INDEX idx_workspaces_user ON workspaces(user_id);

-- ============================================================================
-- REPOSITORIES
-- ============================================================================

-- Mirrors the policy bundle. Reconciled on every bundle reload; policy_version
-- records which bundle produced the current row.
CREATE TABLE repositories (
    id               CHAR(36) NOT NULL,
    tenant_id        VARCHAR(64) NOT NULL,

    policy_repo_id   VARCHAR(255) NOT NULL,
    remote           TEXT NOT NULL,
    forge            VARCHAR(64) NOT NULL,
    default_branch   VARCHAR(255) NOT NULL DEFAULT 'main',

    policy_version   VARCHAR(255) NOT NULL DEFAULT '',

    created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    CONSTRAINT repositories_policy_id_unique UNIQUE (tenant_id, policy_repo_id),
    CONSTRAINT repositories_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- ============================================================================
-- SYNC POINTS
-- ============================================================================

-- The upstream commit whose filtered projection produced a workspace's current
-- state. See docs/PROTOCOL.md section 1: without this, a client's local commit
-- hash is meaningless to the server, because the local tree is a filtered
-- projection and its hashes exist nowhere upstream.
CREATE TABLE sync_points (
    tenant_id        VARCHAR(64) NOT NULL,
    workspace_id     CHAR(36) NOT NULL,
    repository_id    CHAR(36) NOT NULL,
    branch           VARCHAR(255) NOT NULL,

    upstream_commit  VARCHAR(64) NOT NULL,

    -- The bundle that produced this projection. A policy change can widen or
    -- narrow what a workspace should contain, so a sync point taken under an
    -- older bundle may need a resynchronization rather than an incremental
    -- diff.
    policy_version   VARCHAR(255) NOT NULL,

    created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (workspace_id, repository_id, branch),

    CONSTRAINT sync_points_commit_not_empty CHECK (CHAR_LENGTH(TRIM(upstream_commit)) > 0),
    CONSTRAINT sync_points_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT sync_points_workspace_fk FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT sync_points_repository_fk FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

CREATE INDEX idx_sync_points_repo_branch ON sync_points(repository_id, branch);

-- ============================================================================
-- TASKS
-- ============================================================================

-- PostgreSQL declares task_kind, task_state and the rest as enum types shared
-- across tables. MySQL has no CREATE TYPE; ENUM is a column type, so the value
-- list is repeated wherever it is needed. Adding a state means an ALTER on each
-- column rather than one on the type.
CREATE TABLE tasks (
    id              CHAR(36) NOT NULL,
    tenant_id       VARCHAR(64) NOT NULL,

    -- Client-generated, makes submission idempotent. Networks fail mid-push;
    -- without this a retry creates a second upstream commit.
    request_id      VARCHAR(255) NOT NULL,

    kind            ENUM('push', 'pull') NOT NULL,
    state           ENUM('queued', 'running', 'succeeded', 'failed', 'cancelled')
                    NOT NULL DEFAULT 'queued',

    user_id         CHAR(36) NOT NULL,
    workspace_id    CHAR(36) NULL,
    repository_id   CHAR(36) NOT NULL,
    branch          VARCHAR(255) NOT NULL,

    -- Serialization key. At most one task per partition runs at a time; pull
    -- tasks are read-only and leave this NULL so they run fully in parallel.
    partition_key   VARCHAR(512) NULL,

    payload         JSON NOT NULL,
    result          JSON NULL,
    error           JSON NULL,

    attempts        INT NOT NULL DEFAULT 0,

    -- Lease held by the worker currently executing the task. lease_token is a
    -- fencing token: a worker whose lease expired must not be able to complete
    -- the task after another worker picked it up.
    lease_holder     VARCHAR(255) NULL,
    lease_token      VARCHAR(64) NULL,
    lease_expires_at DATETIME(6) NULL,

    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at      DATETIME(6) NULL,
    finished_at     DATETIME(6) NULL,

    PRIMARY KEY (id),
    CONSTRAINT tasks_request_id_unique UNIQUE (tenant_id, request_id),

    CONSTRAINT tasks_lease_consistency CHECK (
        (lease_token IS NULL AND lease_holder IS NULL AND lease_expires_at IS NULL)
        OR
        (lease_token IS NOT NULL AND lease_holder IS NOT NULL AND lease_expires_at IS NOT NULL)
    ),

    CONSTRAINT tasks_finished_after_started CHECK (
        finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at
    ),

    CONSTRAINT tasks_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT tasks_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT tasks_workspace_fk FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL,
    CONSTRAINT tasks_repository_fk FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- The dequeue path: oldest queued task first. PostgreSQL restricts this index
-- to queued rows, which keeps it the size of the backlog. Here it holds every
-- task ever created, so it grows with history rather than with the queue —
-- the strongest argument for pruning finished tasks on this backend.
CREATE INDEX idx_tasks_dispatch ON tasks(state, created_at);

-- Used to test whether a partition is busy, and to compute queue position.
CREATE INDEX idx_tasks_partition ON tasks(partition_key, state);

-- Reaping expired leases.
CREATE INDEX idx_tasks_lease_expiry ON tasks(state, lease_expires_at);

-- PostgreSQL orders these by created_at DESC. MySQL 8 honours a descending
-- index; MariaDB parses DESC and ignores it. Left ascending so the two engines
-- build the same thing, and a backward scan costs nothing measurable here.
CREATE INDEX idx_tasks_user ON tasks(user_id, created_at);
CREATE INDEX idx_tasks_repo ON tasks(repository_id, branch, created_at);

-- ============================================================================
-- ARTIFACTS
-- ============================================================================

-- Content-addressed blobs: uploaded patches and generated filtered patches.
--
-- Addressing by digest gives deduplication, resumable transfer and integrity
-- checking the client can perform itself.
CREATE TABLE artifacts (
    id                 CHAR(36) NOT NULL,
    tenant_id          VARCHAR(64) NOT NULL,

    digest             VARCHAR(255) NOT NULL,
    kind               ENUM('push_patch', 'pull_patch') NOT NULL,

    size_bytes         BIGINT NOT NULL,
    uncompressed_bytes BIGINT NOT NULL,
    encoding           VARCHAR(32) NOT NULL,

    -- Backend-specific locator: a path for the filesystem store, a key for S3.
    locator            TEXT NOT NULL,

    created_at         DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at         DATETIME(6) NULL,

    PRIMARY KEY (id),
    CONSTRAINT artifacts_digest_unique UNIQUE (tenant_id, digest),
    CONSTRAINT artifacts_size_positive CHECK (size_bytes >= 0),
    CONSTRAINT artifacts_expiry_after_creation CHECK (
        expires_at IS NULL OR expires_at > created_at
    ),
    CONSTRAINT artifacts_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

CREATE INDEX idx_artifacts_expiry ON artifacts(expires_at);

-- ============================================================================
-- AUDIT LOG
-- ============================================================================

-- Append-only. This table records what *happened*, which is the half git does
-- not have.
--
-- It deliberately does not answer "who could do what, when, and under which
-- rules?" — the policy bundle's git history answers that, with blame and
-- rollback, which is why rules live in files. What only this table holds is
-- refusals, which leave no trace on the forge because they never reached it,
-- and deliveries, which are the evidence that a read rule was applied.
--
-- One row per denied path, plus one summary row per operation. Recording every
-- allowed path of every push would multiply volume by the size of a changeset
-- for information the summary already carries.
--
-- The enforcement is in migration 0002, so that this file describes the shape
-- and that one describes the guarantee — the same split as PostgreSQL, where
-- 0002 also replaced a weaker mechanism.
CREATE TABLE audit_log (
    id              BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id       VARCHAR(64) NOT NULL,

    occurred_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    actor_user_id   CHAR(36) NULL,
    actor_label     VARCHAR(255) NOT NULL,

    action          VARCHAR(128) NOT NULL,
    repository_id   CHAR(36) NULL,
    branch          VARCHAR(255) NULL,
    path            TEXT NULL,

    effect          ENUM('allow', 'deny') NULL,
    reason          VARCHAR(128) NULL,
    rule_id         VARCHAR(255) NULL,
    guard           VARCHAR(128) NULL,

    policy_version  VARCHAR(255) NOT NULL,
    request_id      VARCHAR(255) NULL,
    task_id         CHAR(36) NULL,

    detail          JSON NULL,

    PRIMARY KEY (id),
    CONSTRAINT audit_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT audit_actor_fk FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT audit_repository_fk FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE SET NULL,
    CONSTRAINT audit_task_fk FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

CREATE INDEX idx_audit_occurred ON audit_log(occurred_at);
CREATE INDEX idx_audit_actor ON audit_log(actor_user_id, occurred_at);
CREATE INDEX idx_audit_repo ON audit_log(repository_id, occurred_at);
CREATE INDEX idx_audit_request ON audit_log(request_id);
