package protocol

// PushMode mirrors enforce.Mode on the wire.
type PushMode string

const (
	// PushModeReject is the default: an unauthorized path fails the whole push.
	PushModeReject PushMode = "reject"

	// PushModeStrip drops unauthorized sections. The client must ask for it
	// explicitly (nit push --drop-unauthorized) and must reconcile afterwards:
	// what lands upstream is no longer what the author committed locally.
	PushModeStrip PushMode = "strip"
)

// PushRequest is sent by the CLI to submit a change.
//
// The patch itself travels as a separate blob upload, so this stays a small
// JSON body that is cheap to log, cheap to reject and easy to inspect.
type PushRequest struct {
	ProtocolVersion string `json:"protocol_version"`

	// RequestID is generated by the client and makes the submission
	// idempotent. Networks fail mid-push; without this, a retry would create a
	// second commit upstream.
	RequestID string `json:"request_id"`

	Repository string `json:"repository"`
	Branch     string `json:"branch"`

	Workspace WorkspaceID `json:"workspace"`

	// BaseSync is the sync point the patch was computed against. The server
	// rejects the push if it no longer matches its record: applying a patch to
	// a base the author never saw is how silent corruption starts.
	BaseSync SyncToken `json:"base_sync"`

	// Message is the commit message for the single squashed commit that lands
	// upstream. nit flattens a submission into one commit: preserving a series
	// would require mapping every local commit hash to a rewritten upstream
	// one, for no benefit a squashed commit with a good message does not give.
	Message string `json:"message"`

	// Patch describes the uploaded payload. Its digest is what the server
	// verifies before decoding anything.
	Patch Blob `json:"patch"`

	Mode PushMode `json:"mode"`

	// DryRun runs authorization and reports the verdict without queueing any
	// work. This is what "nit push --check" uses, and what an editor
	// integration can call on save.
	DryRun bool `json:"dry_run,omitempty"`
}

// PushResponse acknowledges a submission.
type PushResponse struct {
	// TaskID identifies the queued work. It is stable across retries carrying
	// the same RequestID.
	TaskID string `json:"task_id"`

	// Accepted is false for a dry run, and for a push that passed
	// authorization but was not queued.
	Accepted bool `json:"accepted"`

	// Report summarizes the authorization pass. It is populated even on
	// success, so a strip-mode push can tell the developer exactly what was
	// dropped.
	Report PushReport `json:"report"`

	// QueuePosition is how many operations are ahead of this one on the same
	// branch. A push is queued, never refused, when the branch is busy; this
	// number is what the CLI shows while waiting.
	QueuePosition int `json:"queue_position,omitempty"`
}

// PushReport is the authorization outcome of a push.
type PushReport struct {
	PolicyVersion string `json:"policy_version"`

	// FilesTotal, FilesAccepted and FilesDenied count patch sections.
	FilesTotal    int `json:"files_total"`
	FilesAccepted int `json:"files_accepted"`
	FilesDenied   int `json:"files_denied"`

	Denials []Denial `json:"denials,omitempty"`
}

// OK reports whether every file was accepted.
func (r PushReport) OK() bool { return r.FilesDenied == 0 }
