// Package store defines the persistence contract of the control plane, and the
// domain records it stores.
//
// The interfaces here are what the server and the workers depend on; the
// PostgreSQL implementation lives in store/postgres and an in-memory one in
// store/memory. That split is not ceremony: the queue semantics — partition
// exclusion, lease expiry, fencing tokens, idempotent submission — are subtle
// enough that they must be testable without a database, and they must behave
// identically in both implementations. A shared conformance suite enforces that.
package store

import (
	"time"

	"github.com/NitScm/nit/pkg/policy"
	"github.com/NitScm/nit/pkg/protocol"
)

// ID is an opaque record identifier. It is a string rather than a uuid.UUID so
// that the in-memory implementation stays dependency-free and so that a future
// backend is not forced into UUIDs.
type ID string

// User is a person known to the control plane.
//
// Authorization does not read this record: it reads the policy bundle.
// PolicyUserID is the join between the two, and it is what makes a stored task
// attributable to a rule.
type User struct {
	ID       ID
	TenantID policy.TenantID

	PolicyUserID policy.UserID
	Email        string
	DisplayName  string

	Disabled bool

	CreatedAt time.Time
	UpdatedAt time.Time
}

// Workspace is one checkout on one machine.
type Workspace struct {
	ID       ID
	TenantID policy.TenantID
	UserID   ID

	Label string

	CreatedAt  time.Time
	LastSeenAt *time.Time
}

// Session is an authentication token issued to a CLI installation.
//
// Only the hash of the token is stored. A database dump must not yield usable
// credentials, and nothing in nit ever needs to display a token again after it
// has been issued once.
type Session struct {
	ID       ID
	TenantID policy.TenantID
	UserID   ID

	TokenHash []byte
	Label     string

	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

// Active reports whether the session may still authenticate a request.
func (s *Session) Active(now time.Time) bool {
	if s.RevokedAt != nil {
		return false
	}
	if s.ExpiresAt != nil && !now.Before(*s.ExpiresAt) {
		return false
	}
	return true
}

// Repository mirrors an entry of the policy bundle, so that stored records have
// something to reference.
type Repository struct {
	ID       ID
	TenantID policy.TenantID

	PolicyRepoID  policy.RepoID
	Remote        string
	Forge         string
	DefaultBranch string

	PolicyVersion string

	CreatedAt time.Time
	UpdatedAt time.Time
}

// SyncPoint records the upstream commit whose filtered projection produced a
// workspace's current state.
//
// Everything in the protocol is expressed relative to this record: a client's
// own commit hashes describe a filtered tree that exists nowhere upstream, so
// they cannot serve as a diff base.
type SyncPoint struct {
	TenantID     policy.TenantID
	WorkspaceID  ID
	RepositoryID ID
	Branch       string

	UpstreamCommit string

	// PolicyVersion is the bundle that produced the projection. A rule change
	// can widen or narrow what the workspace should hold, in which case an
	// incremental diff is not enough and a resynchronization is required.
	PolicyVersion string

	CreatedAt time.Time
	UpdatedAt time.Time
}

// Lease is a worker's exclusive claim on a task.
type Lease struct {
	// Holder identifies the worker, for diagnostics.
	Holder string

	// Token is a fencing token: every state transition must present it, so a
	// worker whose lease expired cannot complete a task another worker has
	// since picked up.
	Token string

	ExpiresAt time.Time
}

// Expired reports whether the lease has lapsed at the given instant.
func (l *Lease) Expired(now time.Time) bool {
	return l != nil && !now.Before(l.ExpiresAt)
}

// Task is a queued unit of work.
type Task struct {
	ID       ID
	TenantID policy.TenantID

	// RequestID is generated by the client and makes submission idempotent.
	RequestID string

	Kind  protocol.TaskKind
	State protocol.TaskState

	UserID       ID
	WorkspaceID  ID
	RepositoryID ID
	Branch       string

	// PartitionKey serializes execution: at most one task per key runs at a
	// time. Push tasks use "repository:branch"; pull tasks leave it empty and
	// therefore run fully in parallel, being read-only.
	PartitionKey string

	// Payload is the marshalled request, and Result the marshalled outcome.
	// The store treats both as opaque: it has no reason to understand the
	// protocol, and keeping it ignorant means a protocol change does not
	// require a migration.
	Payload []byte
	Result  []byte

	Error *protocol.Error

	Attempts int

	Lease *Lease

	CreatedAt  time.Time
	UpdatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time
}

// Artifact is a stored blob: an uploaded patch or a generated filtered patch.
type Artifact struct {
	ID       ID
	TenantID policy.TenantID

	Digest string
	Kind   ArtifactKind

	Size             int64
	UncompressedSize int64
	Encoding         protocol.Encoding

	// Locator is backend-specific: a path for the filesystem store, a key for
	// object storage.
	Locator string

	CreatedAt time.Time
	ExpiresAt *time.Time
}

// ArtifactKind distinguishes what a blob is for, so that retention can differ:
// an uploaded push patch is disposable once applied, while a generated pull
// patch must survive until the client fetches it.
type ArtifactKind string

const (
	ArtifactPushPatch ArtifactKind = "push_patch"
	ArtifactPullPatch ArtifactKind = "pull_patch"
)

// AuditRecord is one immutable line of the audit log.
type AuditRecord struct {
	ID       int64
	TenantID policy.TenantID

	OccurredAt time.Time

	ActorUserID ID
	// ActorLabel survives the deletion of the user record, so history stays
	// readable after an account is removed.
	ActorLabel string

	Action string

	RepositoryID ID
	Branch       string
	Path         string

	Effect policy.Effect
	Reason policy.Reason
	RuleID string
	Guard  string

	PolicyVersion string
	RequestID     string
	TaskID        ID

	Detail []byte
}
